"""Added proto

Revision ID: 04c842db6e48
Revises: bafbf358e715
Create Date: 2024-11-20 14:05:40.291505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c842db6e48'
down_revision: Union[str, None] = 'bafbf358e715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('observability', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('update_date', sa.String(), nullable=True, server_default="0"))
    op.alter_column('services', 'monitoring',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'monitoring',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('services', 'update_date')
    op.drop_column('services', 'observability')
    # ### end Alembic commands ###
