"""added ci links

Revision ID: 180a7539ee78
Revises: de1aa944a734
Create Date: 2025-01-29 08:53:38.054432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180a7539ee78'
down_revision: Union[str, None] = 'de1aa944a734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('ci_pipeline_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'ci_pipeline_url')
    # ### end Alembic commands ###
