"""cm

Revision ID: 224634ecd827
Revises: 6fc27e8ad8be
Create Date: 2025-03-06 19:44:42.496749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224634ecd827'
down_revision: Union[str, None] = '6fc27e8ad8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('cm_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'cm_key')
    # ### end Alembic commands ###
