"""Added unit_testing

Revision ID: 61055e65da65
Revises: 04c842db6e48
Create Date: 2024-11-26 12:54:27.740065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61055e65da65'
down_revision: Union[str, None] = '04c842db6e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('unit_testing', sa.Boolean(), nullable=True))
    op.alter_column('services', 'update_date',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'update_date',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
    op.drop_column('services', 'unit_testing')
    # ### end Alembic commands ###
