"""added status qg

Revision ID: 6fc27e8ad8be
Revises: 180a7539ee78
Create Date: 2025-01-29 13:17:43.866589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc27e8ad8be'
down_revision: Union[str, None] = '180a7539ee78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('qg_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'qg_status')
    # ### end Alembic commands ###
