"""Update unit_test

Revision ID: 87d4ab4c19fe
Revises: 61055e65da65
Create Date: 2024-11-27 16:22:07.988506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d4ab4c19fe'
down_revision: Union[str, None] = '61055e65da65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'unit_testing',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('services', 'update_date',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'update_date',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'0'::character varying"))
    op.alter_column('services', 'unit_testing',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
