"""added git

Revision ID: de1aa944a734
Revises: 78e7ecb56b9b
Create Date: 2025-01-29 08:10:20.575197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1aa944a734'
down_revision: Union[str, None] = '78e7ecb56b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('git_url', sa.String(), nullable=True))
    op.add_column('services', sa.Column('git_branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'git_branch')
    op.drop_column('services', 'git_url')
    # ### end Alembic commands ###
