"""Unit test enabled

Revision ID: fe08c81e4efc
Revises: 87d4ab4c19fe
Create Date: 2024-11-27 16:34:08.805652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe08c81e4efc'
down_revision: Union[str, None] = '87d4ab4c19fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('unit_testing_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'unit_testing_enabled')
    # ### end Alembic commands ###
